#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname ${BASH_SOURCE[0]})) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

set -euo pipefail

OP_NAME=$(basename $(pwd))

if [ -d .git ]; then
  _ "git found"
  if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
    _warn "git changes detected"
    git status
  fi

  echo
  _ "git clone $(cat .git/config | grep op.git | awk '{print $3}')"
fi

_ "as init complete"
