#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname ${BASH_SOURCE[0]})) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

set -euo pipefail

OP_NAME=$(basename $(pwd))

NEW_OP=1
if [ -d .hugo ]; then
  NEW_OP=0
  mv .hugo/content/notes ./tmp-notes
  rm -rf .hugo
fi

_ "Setup Hugo"
git clone https://github.com/analog-substance/arsenic-hugo.git

rm -rf arsenic-hugo/.git
rm arsenic-hugo/Makefile
rm arsenic-hugo/example/themes/arsenic # remove the symlink that is used just for testing purposes

mv arsenic-hugo/example .hugo
mv arsenic-hugo .hugo/themes/arsenic

if [[ "$NEW_OP" == "1" ]]; then
  mv .hugo/README.md report/sections/
  ln -s report/sections/README.md
else
  rm .hugo/README.md
fi

cd .hugo

if [[ "$NEW_OP" == "1" ]]; then
  mv config.toml ../
  mv sample-finding ../report/findings/first-finding
  mv sample-campaign.md ../report/social
else
  rm config.toml
  rm -rf sample-finding
  rm sample-campaign.md
  mv ../tmp-notes content/notes
fi

ln -s ../config.toml

cd content
ln -srf ../../recon
ln -srf ../../hosts
ls -d ../../report/* | xargs -n 1 ln -srf
mkdir -p notes

cd ../../

ln -sf .hugo/content/notes

_ "Hugo Setup complete"

if [ ! -f Makefile ]; then
  {
    echo -e "report::\n\tcd .hugo; \\"
    echo -e "\thugo server"
    echo -e "addnote::\n\tcd .hugo; \\"
    echo -e "\thugo new \"content/notes/\$\$(date +'%Y-%m-%d_%H%M%S')__\$\$(whoami).md\" --kind note"
    echo -e "update_hugo::\n\tas-setup-hugo"
  } >> Makefile
fi
_ "Setup Hugo complete"
