#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname ${BASH_SOURCE[0]})) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

set -euo pipefail

OP_NAME=$(basename $(pwd))

if [ ! -d ".hugo" ]; then
  _ "Setup Hugo"
  git clone https://github.com/defektive/arsenic-hugo.git

  rm -rf arsenic-hugo/.git
  mv arsenic-hugo/example .hugo
  mkdir .hugo/themes
  mv arsenic-hugo .hugo/themes/arsenic

  mv .hugo/README.md report/sections/
  ln -s report/sections/README.md

  cd .hugo
  mv config.toml ../
  ln -s ../config.toml
  mv sample-finding ../report/findings/first-finding

  cd content
  ln -srf ../../recon
  ln -srf ../../hosts
  ls -d ../../report/* | xargs -n 1 ln -srf

  _ "Hugo Setup complete"
  cd ../../

  if [ ! -f Makefile ]; then
    {
      echo -e "report::\n\tcd .hugo; \\"
      echo -e "\thugo server"
    } >> Makefile
  fi
  _ "Setup Hugo complete"
fi
