#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname $(dirname ${BASH_SOURCE[0]}))) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

FR_THREADS=50

if [ ! -z "$1" ]; then
  FR_THREADS="$1"
fi
set -euo pipefail
mkdir -p recon/domains
find recon/domains/ -maxdepth 1 -type d  | tail -n +2 | while read domain_path; do
  # make sure we have subdomains to process
  if [ -s "$domain_path/subdomains.txt" ]; then
    RECON_FILE="$domain_path/resolv-domains.txt"
    if [[ ! -f "$RECON_FILE" ]] || [[ ! -s "$RECON_FILE" ]] ; then
      mkdir -p "$(dirname $RECON_FILE)"
      root_domain=$(basename "$domain_path")
      _ 'Resoving domains for "'$root_domain'"'
      fast-resolv -c $FR_THREADS -d "$domain_path/subdomains.txt" | tee "$RECON_FILE"
      cat "$RECON_FILE" | sort > sorted
      mv sorted "$RECON_FILE"
    fi
  fi
done

# lets not fail if there are no valid resolutions
set +o pipefail
if compgen -G "recon/domains/*/resolv-domains.txt" > /dev/null; then
  cat recon/domains/*/resolv-domains.txt \
  | grep -P "has address|an alias" \
  | awk '{print $1}' \
  | sort -d \
  | uniq \
  | tee scope-domains-generated-resolved.txt
fi
