#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname $(dirname ${BASH_SOURCE[0]}))) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

mkdir -p recon/ips

set -u

recon_dir="recon/ips"
if [ ! -f "$recon_dir/nmap-https-check-scope-ips-generated-combined.gnmap" ]; then
  _ "Running nmap for ports 443,8443 on ips"
  nmap -p443,8443 -sV -sC -iL scope-ips-generated-combined.txt -oA $recon_dir/nmap-https-check-scope-ips-generated-combined --open
fi

if [ ! -f $recon_dir/ssl-cert-domains.txt ]; then
  _ "Getting domains from certs"
  {
    grep -ohP 'commonName=.+' $recon_dir/nmap-https-check-scope-*.nmap \
    | sed 's/^commonName=//;s/^\*\.//'
    grep -ohP 'Subject Alternative Name: DNS:.+' $recon_dir/nmap-https-check-scope-*.nmap \
    | sed 's/^Subject Alternative Name://;s/ DNS://g;s/^\*\.//;s/,/\n/g'
  } \
    | grep "\." \
    | removeInvalidDomains \
    | sort -d | uniq > $recon_dir/ssl-cert-domains.txt
fi

if [ -f "$recon_dir/ssl-cert-domains.txt" ]; then
  _ "Saving domains to scope"
  cat "$recon_dir/ssl-cert-domains.txt" \
  | removeInvalidDomains \
  | ensureDomainInScope \
  | sort -d \
  | uniq \
  | tee scope-domains-generated-ssl-certs-ips.txt
fi