#! /bin/bash

SCOPE_FILE="$SCOPE_FILE"

if [ ! -z "$1" ] ; then
	SCOPE_FILE="$1"
fi

if [ ! -f "$SCOPE_FILE" ]; then
	echo "you haz no scope file"
	exit 1
fi

OUTPUT_FILE_PREFIX=$(echo "$SCOPE_FILE" | sed 's/\.[a-z]\+$//')

# expand all IPv4 CIDRs
nmap -iL $SCOPE_FILE -sL -n \
  | grep "report for" \
  | awk '{print $5}' \
  > $OUTPUT_FILE_PREFIX-expanded-ipv4.txt

# expand all IPv6 CIDRs
nmap -iL $SCOPE_FILE -sL -n -6 \
  | grep "report for" \
  | awk '{print $5}' \
  > $OUTPUT_FILE_PREFIX-expanded-ipv6.txt

TCP_PORTS=$(echo $(sort -r -k3 /usr/share/nmap/nmap-services | awk '{print $2}' | grep "/tcp" | cut -d/ -f1 | head -n $(arsenic config discover.top-tcp-count)) | sed 's/ /,/g')
UDP_PORTS=$(echo $(sort -r -k3 /usr/share/nmap/nmap-services | awk '{print $2}' | grep "/udp" | cut -d/ -f1 | head -n $(arsenic config discover.top-udp-count)) | sed 's/ /,/g')
TIMING_PROFILE=$(arsenic config discover.timing-profile)

sudo nmap -sn \
  -PP -PA$TCP_PORTS \
  -PS$TCP_PORTS \
  -PU$UDP_PORTS \
  --randomize-hosts \
  --scan-delay 50ms \
  -T$TIMING_PROFILE \
  -iL $OUTPUT_FILE_PREFIX-expanded-ipv4.txt \
  -oA recon/nmap-discovery-$OUTPUT_FILE_PREFIX-ipv4

cat recon/nmap-discovery-$OUTPUT_FILE_PREFIX-ipv4.gnmap | grep Up | awk '{print $2}' > $OUTPUT_FILE_PREFIX-active-ipv4.txt

sudo nmap -6 -sn \
  -PA$TCP_PORTS \
  -PS$TCP_PORTS \
  -PU$UDP_PORTS \
  --randomize-hosts \
  --scan-delay 50ms \
  -T$TIMING_PROFILE \
  -iL $OUTPUT_FILE_PREFIX-expanded-ipv6.txt \
  -oA recon/nmap-discovery-$OUTPUT_FILE_PREFIX-ipv6

cat recon/nmap-discovery-$OUTPUT_FILE_PREFIX-ipv6.gnmap | grep Up | awk '{print $2}' > $OUTPUT_FILE_PREFIX-active-ipv6.txt
