#! /bin/bash

mkdir -p recon/domains recon/discover recon/ips

set -u

function _ {
  echo "[+] $@"
}

function ensureInScope {
  in_scope=$(echo $(cat scope-domains.txt | sed 's/\./\\./g;s/^/(.+\\.)?/g') | sed 's/ /|/g')
  if [[ -n "$in_scope" ]]; then
    grep -P "^$in_scope$"
  else
    grep -P '.*'
  fi
}

if [ ! -f "recon/nmap-https-check-scope-domains-generated-combined.gnmap" ]; then
  _ "Running nmap for ports 443,8443 on domains"
  nmap -p443,8443 -sV -sC -iL scope-domains-generated-combined.txt -oA recon/nmap-https-check-scope-domains-generated-combined --open
fi

if [ ! -f "recon/nmap-https-check-scope-ips-generated-combined.gnmap" ]; then
  _ "Running nmap for ports 443,8443 on ips"
  nmap -p443,8443 -sV -sC -iL scope-ips.txt -oA recon/nmap-https-check-scope-ips-generated-combined --open
fi

if [ ! -f recon/ssl-cert-domains.txt ]; then
  _ "Getting domains from certs"
  {
    grep -ohP 'commonName=.+' recon/nmap-https-check-scope-*.nmap \
    | sed 's/^commonName=//;s/^\*\.//'
    grep -ohP 'Subject Alternative Name: DNS:.+' recon/nmap-https-check-scope-*.nmap \
    | sed 's/^Subject Alternative Name://;s/ DNS://g;s/^\*\.//;s/,/\n/g'
  } \
    | grep "\." \
    | as-prune-blacklisted-domains \
    | sort -h | uniq > recon/ssl-cert-domains.txt
fi


find recon/domains/ -maxdepth 1 -type d  | tail -n +2 | while read domain_path; do
  if [ ! -f "$domain_path/ssl-cert-domains.txt" ]; then
    domain=$(echo "$domain_path" | cut -d/ -f3)

    cat scope-domains* \
    | grep -P "$(echo $domain| sed 's/\./\\./g')$" \
    | as-prune-blacklisted-domains > "$domain_path/combined-domains.txt"

  fi
done




_ "Saving domains to scope"
cat recon/ssl-cert-domains.txt \
| ensureInScope \
| sort -h \
| uniq \
| tee scope-domains-generated-ssl-certs.txt
