#! /bin/bash

GIT=1
if [ ! -d .git ]; then
  GIT=0
fi

set -euo pipefail

WEB_PORTS="80,443,3000,8000,8001,8080,8443"

function gitPull {
  if [ $GIT -eq 1 ]; then
    if ! git pull > /dev/null 2>&1 ; then
      echo "[!] pull failed" >&2
    fi
  fi
}

function gitCommit {
  if [ $GIT -eq 1 ]; then
    path="$1"
    msg="$2"
    git add "$path"

    if git commit -m "$msg" ; then
      if ! git pull --rebase ; then
        git commit -am "wtf is this..."
        git pull --rebase
      fi
      git push
    else
      echo "nothing happened"
    fi
  fi
}

if [ ! -d "recon/aquatone-domains" ] ; then
  mkdir -p recon/aquatone-domains
  touch recon/aquatone-domains/.keep

  gitCommit "." "aquatone domains"

  cat scope-domains* | sort -u | aquatone -ports $WEB_PORTS -out recon/aquatone-domains
  # remove UTF BOM, this fixes aquatone being rendered in hugo
  find recon/aquatone-domains -name '*.html' -exec sed -i '1s/^\xEF\xBB\xBF//' {} \;

  gitCommit "." "aquatone domains end "
fi
