#! /bin/bash

GIT=1
if [ ! -d .git ]; then
  GIT=0
fi

set -euo pipefail

WEB_PORTS="80,443,3000,8000,8001,8080,8443"


find recon/domains/ -maxdepth 1 -type d  | tail -n +2 | while read domain_path; do
  if [ ! -d "$domain_path/aquatone-domains" ] ; then
    mkdir -p  "$domain_path/aquatone-domains"
    domain=$(echo "$domain_path" | cut -d/ -f3)

    cat scope-domains* \
    | grep -P "$(echo $domain| sed 's/\./\\./g')$" \
    | sort -u \
    | aquatone -ports $WEB_PORTS -out  "$domain_path/aquatone-domains"

    # remove UTF BOM, this fixes aquatone being rendered in hugo
    find r"$domain_path/aquatone-domains" -name '*.html' -exec sed -i '1s/^\xEF\xBB\xBF//' {} \;
  fi
done
