#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname $(dirname ${BASH_SOURCE[0]}))) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

mkdir -p recon/domains recon/discover recon/ips

function root_domain_recon {
  domain=$(echo $1 | tr 'A-Z' 'a-z')
  if ! echo "$domain" | as-prune-blacklisted-domains | grep "$domain" > /dev/null ; then
    _warn "Skipping common domain: $domain"
  else
    mkdir -p "recon/domains/$domain"

    RECON_FILE="recon/domains/$domain/amass-enum-active.txt"
    if [ ! -f "$RECON_FILE" ] ; then
      _ "amass enum active $domain"

      amass enum -src -active -d "$domain" \
      | tee "$RECON_FILE"
    fi

    RECON_FILE="recon/domains/$domain/amass-intel.txt"
    if [ ! -f "$RECON_FILE" ] ; then
      _ "amass intel whois $domain"
      amass intel -d "$domain" -whois \
      | tee "$RECON_FILE"
    fi

    {
      if [ -f "recon/domains/$domain/amass-enum-active.txt" ]; then
        cat "recon/domains/$domain/amass-enum-active.txt" 2>/dev/null | awk '{print $2}'
      fi

      if [ -f "recon/domains/$domain/amass-intel.txt" ]; then
        cat "recon/domains/$domain/amass-intel.txt"
      fi
    } \
    | grep -P "$(echo "$domain" | sed 's/\./\\./g')\$" \
    | sort -d \
    | uniq > "recon/domains/$domain/subdomains-amass.txt"
  fi
}

# Recon root domains
_ "Checking for subdomains on root domains"
getRootDomains | while read domain; do
  root_domain_recon "$domain"
done

if compgen -G "recon/domains/*/amass-enum-active.txt" > /dev/null 2>&1; then
  _ "saving scope from amass enum active"
  cat recon/domains/*/amass-enum-active.txt 2>/dev/null \
  | awk '{print $2}' \
  | sort -d \
  | uniq \
  | ensureDomainInScope \
  | tee scope-domains-generated-amass-enum-active.txt
fi

if compgen -G "recon/domains/*/amass-intel.txt" > /dev/null 2>&1; then
  _ "saving scope from amass intel whois"
  cat recon/domains/*/amass-intel.txt 2>/dev/null \
  | sort -d \
  | uniq \
  | ensureDomainInScope \
  | tee scope-domains-generated-amass-intel-whois.txt
fi
_ "Combine all discovered domains"
getAllDomains
