#! /bin/bash

function _ {
  echo "[+] $@"
}

mkdir -p recon/domains recon/discover recon/ips

declare -a root_domain_commands=("whois")
declare -a domain_commands=("host")
declare -a dig_commands=("TXT" "NS" "MX" "SOA" "A")
declare -a ip_commands=("whois")

REMOVE_DOMAIN_REGEX="(\._domainkey\.|hscoscdn10\.net|sites\.hubspot\.net|amazonaws\.com|azurewebsites\.net|azurewebsites\.windows\.net|azure\.com|cloudapp\.net|readthedocs\.io|my\.jobs|googlehosted\.com|readthedocs\.org)$"

# Right now just gonna ignore these.
NON_ROOT_DOMAIN_REGEX="co\.|com\.|herokuapp\."
function getRootDomains {
  ## Lets get a unique list of root domains
  # cat all domains
  # remove *. prefix
  # remove email addr prefixes
  # remove problematic domains
  # print last 2 octets in the domain
  # remove things like co.uk, com.uk
  cat scope-domains* \
  | removeInvalidThings \
  | awk -F. '{print $(NF-1) "." $NF}' \
  | grep -vP "$NON_ROOT_DOMAIN_REGEX" \
  | sort -h | uniq \
  | tee scope-domains-generated-root.txt
}

function getAllDomains {
  # create a combined scope file
    cat scope-domains* \
    | removeInvalidThings \
    | cat - scope-domains.txt \
    | sort -h |  uniq \
    | tee scope-domains-generated-combined.txt
}

function removeInvalidThings {
  # remove *. prefix
  # remove email addr prefixes
  # remove IP addrs
  # remove IPv6 addrs
  # remove domain regex
  sed 's/^\*\.//g' \
  | sed 's/^[^@]\+@//g' \
  | tr 'A-Z' 'a-z' \
  | grep -vP "^([0-9]{1,3}\.){3}[0-9]{1,3}$" \
  | grep -vP "$REMOVE_DOMAIN_REGEX" \
  | grep -P '^[a-z0-9_\-\.]+$' \
  | as-prune-blacklisted-domains \
  | sort -h | uniq
}

function domain_recon {
  domain=$(echo $1 | tr 'A-Z' 'a-z')
  if echo "$domain" | grep -P "$REMOVE_DOMAIN_REGEX" > /dev/null ; then
    echo "[!] Skipping common domain: $domain" >&2
  else
    for cmd in "${domain_commands[@]}";  do
        $cmd $domain | tr 'A-Z' 'a-z' &
    done
    wait
  fi
}

function root_domain_recon {
  domain=$(echo $1 | tr 'A-Z' 'a-z')
  if echo "$domain" | grep -P "$REMOVE_DOMAIN_REGEX" > /dev/null ; then
    echo "[!] Skipping common domain: $domain"
  else
    mkdir -p "recon/domains/$domain"

    RECON_FILE="recon/domains/$domain/amass-enum-active.txt"
    if [ ! -f "$RECON_FILE" ] ; then
      _ "amass enum active $domain"

      amass enum -src -active -d "$domain" \
      | tee "$RECON_FILE"
    fi

    RECON_FILE="recon/domains/$domain/amass-intel.txt"
    if [ ! -f "$RECON_FILE" ] ; then
      _ "amass intel whois $domain"
      amass intel -d "$domain" -whois \
      | tee "$RECON_FILE"
    fi

    for cmd in "${root_domain_commands[@]}";  do
      if [ ! -f "recon/domains/$domain/$cmd.txt" ]; then
        echo "[+] running $domain $cmd"

        $cmd $domain | tr 'A-Z' 'a-z' > "recon/domains/$domain/$cmd.txt" &
      else
        echo "[!] skipping $domain $cmd"
      fi
    done
    for cmd in "${dig_commands[@]}";  do
      if [ ! -f "recon/domains/$domain/dig-$cmd.txt" ]; then
        echo "[+] running dig $domain $cmd"

        dig $cmd $domain | tr 'A-Z' 'a-z' > "recon/domains/$domain/dig-$cmd.txt" &
      else
        echo "[!] skipping dig $domain $cmd"
      fi
    done
    wait
  fi
}

function ensureInScope {
  grep -P "^$(echo $(cat scope-domains.txt | sed 's/\./\\./g;s/^/(.+\\.)?/g') | sed 's/ /|/g')$"
}

_ "Get root domains"
getRootDomains > /dev/null

_ "saving scope from amass enum active"
cat recon/domains/*/amass-enum-active.txt 2>/dev/null \
| awk '{print $2}' \
| ensureInScope \
| sort -h \
| uniq \
| tee scope-domains-generated-amass-enum-active.txt

_ "saving scope from amass intel whois"
cat recon/domains/*/amass-intel.txt 2>/dev/null \
| ensureInScope \
| sort -h \
| uniq \
| tee scope-domains-generated-amass-intel-whois.txt

_ "Combine all discovered domains"
getAllDomains > /dev/null

# Recon root domains
_ "Recon on root domains"
getRootDomains | while read domain; do
  root_domain_recon "$domain"
done

_ "Combine all discovered domains"
getAllDomains
