#! /bin/bash

CMD=""
ARG=""
if [ ! -z "$1" ]; then
  CMD="$1"
fi

if [ ! -z "$2" ]; then
  ARG="$2"
fi


if [ -z "$CMD" ] ; then
  CMD="scan"
fi

# set -x
set -euo pipefail

function getHosts {
  if ! git pull > /dev/null 2>&1 ; then
    echo "[!] pull failed" >&2
  fi

  {
    find hosts -name 'nmap-*'  | cut -d/ -f2
    ls -d hosts/* | cut -d/ -f2
  } | ar-prune-blacklisted-ips | sort -h | uniq -c | grep -P "^\s+1 " | awk '{print $2}' | sort -R
}

function scanHost {
  host="$1"
  echo checking $host

  if ! compgen -G "hosts/$host/recon/nmap-punched*" > /dev/null 2>&1; then
    echo setting up host
    mkdir -p "hosts/$host/recon"
    if [ ! -f "hosts/$host/recon/nmap-punched-quick.xml" ]; then
      touch "hosts/$host/recon/nmap-punched-quick.xml"
      git add "hosts/$host/recon/"
      git commit -m "new host: $host"
      git pull --rebase
      git push
    fi

    cd "hosts/$host"

    ar-recon-discover-services "$host" &
    sleep 1
    git add .
    git commit -m "nmap"
    if ! git pull --rebase ; then
      git commit -am "wtf is this..."
      git pull --rebase
    fi
    git push
    echo wait for nmap...
    wait
    cd -
    git stash
    git pull --rebase
    git stash pop
    ar-update-flags.sh git

    git add "hosts/$host"
    if git commit -m "recon host: $host" ; then
      git push
    else
      echo "nothing happened"
    fi
  fi
  echo host check complete

  ARG=$(head -n1 <<<$(getHosts | sort -R))
  if [ ! -z "$ARG" ] ; then
    exec $0 scan "$ARG"
  fi
}

if [ "$CMD" == "list" ]; then
  getHosts
  exit
fi

if [ "$CMD" == "scan" ] ; then
  if [ -z "$ARG" ] ; then
    ARG=$(head -n1 <<<$(getHosts | sort -R))
    echo "[!] Auto selected $ARG"
  fi
  scanHost "$ARG"
fi
