#! /bin/bash

CMD=""
ARG=""
if [ ! -z "$1" ]; then
  CMD="$1"
fi

if [ ! -z "$2" ]; then
  ARG="$2"
fi


if [ -z "$CMD" ] ; then
  CMD="scan"
fi

GIT=1
if [ ! -d .git ]; then
  GIT=0
fi

# set -x
set -euo pipefail

function gitPull {
  if [ $GIT -eq 1 ]; then
    if ! git pull > /dev/null 2>&1 ; then
      echo "[!] pull failed" >&2
    fi
  fi
}

function gitCommit {
  if [ $GIT -eq 1 ]; then
    path="$1"
    msg="$2"
    git add "$path"

    if git commit -m "$msg" ; then
      if ! git pull --rebase ; then
        git commit -am "wtf is this..."
        git pull --rebase
      fi
      git push
    else
      echo "nothing happened"
    fi
  fi
}

function getHosts {
  gitPull

  {
    find hosts -name 'nmap-punched-udp*'  | cut -d/ -f2
    ls -d hosts/* | cut -d/ -f2
  } | as-prune-blacklisted-ips | sort -h | uniq -c | grep -P "^\s+1 " | awk '{print $2}' | sort -R
}

function scanHost {
  host="$1"
  if [ "$host" == "" ]; then
    return
  fi
  echo checking $host

  if ! compgen -G "hosts/$host/recon/nmap-punched-udp*" > /dev/null 2>&1; then
    echo setting up host
    mkdir -p "hosts/$host/recon"
    if [ ! -f "hosts/$host/recon/nmap-punched-udp.nmap" ]; then
      touch "hosts/$host/recon/nmap-punched-udp.nmap"
      gitCommit "hosts/$host/recon/" "new host: $host"
    fi

    cd "hosts/$host"

    nmap -oA recon/nmap-punched-udp -sUV "$host"
    
    gitCommit "hosts/$host" "recon host: $host"

  fi
  echo host check complete

  ARG=$(head -n1 <<<$(getHosts | sort -R))
  if [ ! -z "$ARG" ] ; then
    exec $0 scan "$ARG"
  fi
}

if [ "$CMD" == "list" ]; then
  getHosts
  exit
fi

if [ "$CMD" == "scan" ] ; then
  if [ -z "$ARG" ] ; then
    ARG=$(head -n1 <<<$(getHosts | sort -R))
    if [ "$ARG" == "" ]; then
      exit
    fi
    echo "[!] Auto selected $ARG"
  fi
  scanHost "$ARG"
fi
