#! /bin/bash
ME=$0
CMD=""
ARG=""
if [ ! -z "$1" ]; then
  CMD="$1"
fi

if [ ! -z "$2" ]; then
  ARG="$2"
fi

if [ -z "$CMD" ] ; then
  CMD="scan"
fi

set -euo pipefail

WEB_PORTS="80,443,3000,8000,8001,8080,8443"

function getURLs {
  {
    set +o pipefail
    cat recon/*.gobuster-initial.txt \
    | grep -P "Status: 2"  \
    | grep -viP "\.(png|jpe?g|ico|css|gif|js)$"
    set -o pipefail
  } \
  | awk '{print $1}' \
  | sort -h | uniq
}

function getHosts {
  if ! git pull > /dev/null 2>&1 ; then
    echo "[!] pull failed" >&2
  fi

   {
     find hosts -name 'gobuster.*.gobuster-initial.txt' -size +0 | cut -d/ -f2 | sort -h | uniq
     find hosts -name 'aquatone-gobuster-initial.txt' | cut -d/ -f2 | sort -h | uniq
   } | sort | uniq -c | grep "1 " | awk '{print $2}' | while read host; do
   cd hosts/$host
    urls=$(getURLs | wc -l)
    if [ "$urls" != "0" ]; then
      echo $host
    fi
    cd - > /dev/null
  done | sort -h | uniq
}

function scanHost {
  host="$1"
  echo checking $host

  if [ ! -f "hosts/$host/recon/aquatone-gobuster-initial.txt" ] ; then
    echo preparing to aquatone $host

    cd "hosts/$host"
    getURLs \
    | tee "recon/aquatone-gobuster-initial.txt"

    git add .
    git commit -m "aquatone start $host"
    if ! git pull --rebase ; then
      echo something went wrong help
      exit
    fi
    if ! git push ; then
      git pull --rebase

      if ! git push ; then
        echo something went wrong help
        exit
      fi

    fi

    cat "recon/aquatone-gobuster-initial.txt" | aquatone -ports $WEB_PORTS -out recon/aquatone-gobuster-initial
    ar-update-flags.sh git
    # remove UTF BOM, this fixes aquatone being rendered in hugo
    find . -name '*.html' -exec sed -i '1s/^\xEF\xBB\xBF//' {} \;

    git add .
    cd - > /dev/null

    if git commit -m "aquatone end $host" ; then
      if ! git pull --rebase ; then
        echo something went wrong help
        echo I was trying to pull before pushing up the aaquatone results
        exit
      fi
      if ! git push ; then
        git pull --rebase

        if ! git push ; then
          echo something went wrong help
          exit
        fi
      fi
    else
      echo not sure what happened. but i couldnt commit
    fi
  fi

  echo host check complete
  sleep 10

  ARG=$(head -n1 <<<$($ME list))
  if [ ! -z "$ARG" ] ; then
    exec $ME scan "$ARG"
  fi
}

if [ -z "$CMD" ] ; then
  echo "aquatone-next [ list | scan [ hostname/ip ] ]"
  exit
fi

if [ "$CMD" == "list" ]; then
  getHosts
  exit
fi

if [ "$CMD" == "scan" ] ; then
  if [ -z "$ARG" ] ; then
    ARG=$(head -n1 <<<$(getHosts | sort -R))
    echo "[!] Auto selected $ARG"
  fi
  scanHost "$ARG"
fi
