#! /bin/bash
ME=$0
CMD=""
ARG=""
if [ ! -z "$1" ]; then
  CMD="$1"
fi

if [ ! -z "$2" ]; then
  ARG="$2"
fi

if [ -z "$CMD" ] ; then
  CMD="scan"
fi

GIT=1
if [ ! -d .git ]; then
  GIT=0
fi

set -euo pipefail

WEB_PORTS="80,443,3000,8000,8001,8080,8443"

function gitPull {
  if [ $GIT -eq 1 ]; then
    if ! git pull > /dev/null 2>&1 ; then
      echo "[!] pull failed" >&2
    fi
  fi
}

function gitCommit {
  if [ $GIT -eq 1 ]; then
    path="$1"
    msg="$2"
    git add "$path"

    if git commit -m "$msg" ; then
      if ! git pull --rebase ; then
        git commit -am "wtf is this..."
        git pull --rebase
      fi
      git push
    else
      echo "nothing happened"
    fi
  fi
}

function getURLs {
  {
    set +o pipefail
    cat recon/*.wordlist-content-discovery.txt \
    | grep -P "Status: 2"  \
    | grep -viP "\.(png|jpe?g|ico|css|gif|js)$"
    set -o pipefail
  } \
  | awk '{print $1}' \
  | sort -h | uniq
}

function getHosts {
  gitPull

   {
     find hosts -name 'gobuster.*.wordlist-content-discovery.txt' -size +0 | cut -d/ -f2 | sort -h | uniq
     find hosts -name 'wordlist-content-discovery.txt' | cut -d/ -f2 | sort -h | uniq
   } | sort | uniq -c | grep "1 " | awk '{print $2}' | while read host; do
   cd hosts/$host
    urls=$(getURLs | wc -l)
    if [ "$urls" != "0" ]; then
      echo $host
    fi
    cd - > /dev/null
  done | sort -h | uniq
}

function scanHost {
  host="$1"
  echo checking $host

  if [ ! -f "hosts/$host/recon/wordlist-content-discovery.txt" ] ; then
    echo preparing to aquatone $host

    cd "hosts/$host"
    getURLs \
    | tee "recon/wordlist-content-discovery.txt"

    gitCommit "." "aquatone start $host"

    cat "recon/wordlist-content-discovery.txt" | aquatone -ports $WEB_PORTS -out recon/aquatone-wordlist-content-discovery
    # remove UTF BOM, this fixes aquatone being rendered in hugo
    find . -name '*.html' -exec sed -i '1s/^\xEF\xBB\xBF//' {} \;

    gitCommit "." "aquatone end $host"

    cd - > /dev/null
  fi

  echo host check complete
  sleep 10

  ARG=$(head -n1 <<<$($ME list))
  if [ ! -z "$ARG" ] ; then
    exec $ME scan "$ARG"
  fi
}

if [ -z "$CMD" ] ; then
  echo "aquatone-next [ list | scan [ hostname/ip ] ]"
  exit
fi

if [ "$CMD" == "list" ]; then
  getHosts
  exit
fi

if [ "$CMD" == "scan" ] ; then
  if [ -z "$ARG" ] ; then
    ARG=$(head -n1 <<<$(getHosts | sort -R))
    if [ "$ARG" == "" ]; then
      exit
    fi
    echo "[!] Auto selected $ARG"
  fi
  scanHost "$ARG"
fi
