#! /bin/bash

CMD=""
ARG=""
if [ ! -z "$1" ]; then
  CMD="$1"
fi

if [ ! -z "$2" ]; then
  ARG="$2"
fi


if [ -z "$CMD" ] ; then
  CMD="scan"
fi

GIT=1
if [ ! -d .git ]; then
  GIT=0
fi

# set -x
set -euo pipefail

function gitPull {
  if [ $GIT -eq 1 ]; then
    if ! git pull > /dev/null 2>&1 ; then
      echo "[!] pull failed" >&2
    fi
  fi
}

function gitCommit {
  if [ $GIT -eq 1 ]; then
    path="$1"
    msg="$2"
    mode="$3"
    git add "$path"

    if git commit -m "$msg" ; then
      if ! git pull --rebase ; then
        echo '[!] pull rebase failed'
        if [ "$mode" == "reset" ] ; then
          echo '[!] reset to origin'
          git reset --hard origin/master
          exit 2
        fi
        echo '[!] not sure what to do. i guess i will git add and hope it works'
        git commit -am "not sure what this is"
        git pull --rebase
      fi
      git push
    else
      echo "nothing happened"
    fi
  fi
}

function getHosts {
  gitPull

  {
    find hosts -name 'nmap-*tcp*'  | cut -d/ -f2
    ls -d hosts/* | cut -d/ -f2
  } | as-prune-blacklisted-ips | sort -h | uniq -c | grep -P "^\s+1 " | awk '{print $2}' | sort -R
}

function scanHost {
  host="$1"
  if [ "$host" == "" ]; then
    return
  fi

  if ! compgen -G "hosts/$host/recon/nmap-punched*tcp*" > /dev/null 2>&1; then
    mkdir -p "hosts/$host/recon"
    if [ ! -f "hosts/$host/recon/nmap-punched-quick-tcp.xml" ]; then
      echo lock > "hosts/$host/recon/nmap-punched-quick-tcp.xml"
      gitCommit "hosts/$host/recon/nmap-punched-quick-tcp.xml" "new host: $host" "reset"
    fi

    cd "hosts/$host"

    as-recon-discover-services "$host"

    gitCommit "." "recon host: $host"

    cd -

  fi
  echo host check complete

  ARG=$(head -n1 <<<$(getHosts | sort -R))
  if [ ! -z "$ARG" ] ; then
    exec $0 scan "$ARG"
  fi
}

if [ "$CMD" == "list" ]; then
  getHosts
  exit
fi

if [ "$CMD" == "scan" ] ; then
  if [ -z "$ARG" ] ; then
    ARG=$(head -n1 <<<$(getHosts | sort -R))
    if [ "$ARG" == "" ]; then
      exit
    fi
    echo "[!] Auto selected $ARG"
  fi
  scanHost "$ARG"
fi
