#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname $(dirname ${BASH_SOURCE[0]}))) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

CMD=""
ARG=""
if [ ! -z "$1" ]; then
  CMD="$1"
fi

if [ ! -z "$2" ]; then
  ARG="$2"
fi

if [ -z "$CMD" ] ; then
  CMD="scan"
fi

# set -x
set -euo pipefail

function getHosts {
  gitPull

  {
    find hosts -name 'nmap-udp*'  | cut -d/ -f2
    ls -d hosts/* | cut -d/ -f2
  } | sort -d | uniq -c | grep -P "^\s+1 " | awk '{print $2}' | sort -R
}

function scanHost {
  host="$1"
  if [ "$host" == "" ]; then
    return
  fi

  _ "Port Scan / UDP / $host / checking"
  if ! compgen -G "hosts/$host/recon/nmap-udp*" > /dev/null 2>&1; then
    _info "Port Scan / UDP / $host / preparing"
    mkdir -p "hosts/$host/recon"
    gitLock "hosts/$host/recon/nmap-udp.nmap" "UDP port scan lock: $host"

    cd "hosts/$host"
    _info "Port Scan / UDP / $host / running"
    nmap --privileged --stylesheet /static/nmap.xsl -oA recon/nmap-udp -sUV -p- -Pn --max-rtt-timeout 100ms --min-rate 1000 --version-intensity 0 "$host"
    chown -R $USER:$USER recon
    gitCommit "." "UDP port scan complete: $host"
    cd -

    _info "Port Scan / UDP / $host / complete"
  fi

  ARG=$(head -n1 <<<$(getHosts | sort -R))
  if [ ! -z "$ARG" ] ; then
    exec $0 scan "$ARG"
  fi


  set +e
  if grep lock hosts/*/recon/nmap-udp.nmap | grep :lock > /dev/null; then
    _warn "other UDP port scans are still running... lets wait before continuing"
    exit 1
  fi
}

gitPull

if [ "$CMD" == "list" ]; then
  getHosts
  exit
fi

if [ "$CMD" == "scan" ] ; then
  if [ -z "$ARG" ] ; then
    ARG=$(head -n1 <<<$(getHosts | sort -R))
    if [ "$ARG" == "" ]; then
      exit
    fi
    _warn "Auto selected $ARG"
  fi
  scanHost "$ARG"
fi
