#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname $(dirname ${BASH_SOURCE[0]}))) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

arsenic hosts -p http | nuclei -project -t technologies -o "/tmp/nuclei-technologies.txt"
if [ ! -s "/tmp/nuclei-technologies.txt" ]; then
  exit
fi

arsenic hosts -p http | while read url; do
  hostname=$(echo "$url" | sed 's|https\?://||')
  hostDir=$(arsenic hosts -H "$hostname" --paths)
  output="$hostDir/recon/nuclei-technologies.$(echo "$url" | sed 's|://|\.|').txt"

  grep -F "$url" /tmp/nuclei-technologies.txt > "$output"

  if [[ -e "$output" && ! -s "$output" ]]; then
    rm $output 2> /dev/null
  fi
done
