#! /bin/bash

export COLUMNS=140
find . -name 'nmap-punched*.xml' | while read file; do
  echo '[!] checking '"$file"
  searchsploit --colour --nmap "$file" 2>/dev/null \
  | tee "$file.searchsploit.txt"
done
