#! /bin/bash

####
## BEGIN: Load common functions

if [ -z "$ARSENIC_PATH" ]; then
  pushd $(dirname $(dirname $(dirname ${BASH_SOURCE[0]}))) > /dev/null
  export ARSENIC_PATH=`pwd`
  popd > /dev/null
fi

if [ -f "$ARSENIC_PATH/etc/common.sh" ]; then
  source "$ARSENIC_PATH/etc/common.sh"
fi

## END: Load common functions
####

# Don't run any quick nmap scans through searchsploit
export COLUMNS=140
find . -name 'nmap-*.xml' -and -not -name '*quick*' | while read file; do
  echo '[!] checking '"$file"
  searchsploit --colour --nmap "$file" 2>/dev/null \
  | tee "$file.searchsploit.txt"
done
