#! /bin/bash
FR_THREADS=100

if [ ! -z "$1" ]; then
  FR_THREADS="$1"
fi

set -uo pipefail

REMOVE_IP_REGEX="(104\.(1[6-9]|2[0-9]|3[01])|184\.(2[4-9]|3[01])|104\.(6[4-9]|[7-9][0-9]|[12][0-9]{2})|23\.[01][0-5]?|96\.[67]|23\.(3[2-9]|[45][0-9]|6[0-7])|136\.147)\.[0-9]{1,3}\.[0-9]{1,3}"
PRIVATE_IP_REGEX="(127\.[0-9]{1,3}\.|10\.[0-9]{1,3}\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.)[0-9]{1,3}\.[0-9]{1,3}"

# create scope ips from domains
grep -riP "has (IPv6 )?address" recon/domains/  \
  | awk '{print $NF}' \
  | sort -h | uniq \
  | grep -vP "$REMOVE_IP_REGEX" \
  | as-prune-blacklisted-ips  \
  | tee scope-ips-client-domains.txt

## maybe this should be in the IPs?
cat scope-ips* | as-prune-blacklisted-ips | cat - scope-ips.txt | sort -h | uniq > scope-ips-combined.txt

# Create IP Scope files for public and private addresses
cat scope-ips-combined.txt | grep -vP "^$PRIVATE_IP_REGEX\$" | grep -v ":" | sort -h | uniq > scope-ips-public-ipv4.txt

# there has to be a better way. we dont want the scrip to exit if there are no matches
cat scope-ips-combined.txt | grep -vP "^$PRIVATE_IP_REGEX\$" | grep ":" | sort -h | uniq > scope-ips-public-ipv6.txt
cat scope-ips-combined.txt | grep -P "^$PRIVATE_IP_REGEX\$" | sort -h | uniq > scope-ips-private-ipv4.txt



RECON_FILE="recon/ips/resolv-ips.txt"
if [ ! -f "$RECON_FILE" ] ; then
  echo '[+] Resoving IP Addresses'
  fast-resolv -c $FR_THREADS -d scope-ips-public*.txt | tee "$RECON_FILE"
  cat "$RECON_FILE" | sort > sorted
  mv sorted "$RECON_FILE"
fi
